---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezbake
  namespace: foo
  labels:
    app: ezbake
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ezbake
  template:
    metadata:
      labels:
        app: ezbake
    spec:
      containers:
        - name: ezbake
          command: ["./ezbake"]
          image: ezbake:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: "ezbake=trace,warn"
---
apiVersion: v1
kind: Service
metadata:
  name: ezbake
  namespace: foo
spec:
  type: ClusterIP
  selector:
    app: ezbake
  ports:
    - port: 8008
      targetPort: 8008
      name: grpc
