name: Deploy Images to GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: 'Login to Registry'
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
  
      - name: 'Build Image'
        run: |
          docker build --file ./scripts/Dockerfile-multiarch  \
                       --platform=linux/arm64,linux/amd64 \
                       --push \
                       --tag ${{env.REGISTRY}}/junction-labs/${{env.IMAGE_NAME}}:latest \
                       .
